### ISSUE TITLE
Funding allocation is not working properly 

### ISSUE THREAD

**Issue by sepu85** [AutarkLabs/planning-suite#905] opened 2019-05-10 12:27 UTC
when funding an Allocation vault from the finance App, it's not being possible because of the following two reasons:
- when creating the funding vote from an address having the 66% of the voting power, the transaction/votation is not generated at all.
- when creating the funding vote from an address having the 33% (DAO creator) of the voting power, the transaction/votation gets created, but when voting yes from the 66% address the following messages appears in Metamask: `ALERT: Error en transacción. Se produjo una excepción en el código del contrato.` which stands for `ALERT: Error in transaction. An exception has been produced in the contact code`.

The DAO I'm using to test the Allocation App is:
https://rinkeby.autark.xyz/#/mytestdapp.aragonid.eth/0x1d274e0e3849408545e3a4f8af3d0de57951713b

**Comment by sepu85** [comment] 2019-05-10 13:39
here the transaction referred to the exception error

https://rinkeby.etherscan.io/tx/0x41fe52087bda0a72da14c87936fb7cd3a166c64149d66d214651b483463380a8

**Comment by topocount** [comment] 2019-05-10 16:02
Hi @sepu85 we're actively working to understand the root cause of this issue. Thanks for logging it

**Comment by topocount** [comment] 2019-05-10 17:34
Hi @sepu85, Here's our explanation for this limitation and the behavior you're seeing:

# Root Cause
Being able to send funds from Finance to Allocations is a security-related gas issue. The Allocations account is a payable contract that forwards ETH sent it's way back to the Allocations contract. This action obviously requires more gas than a simple transfer to a non-contract address, or a payable contract that has no logic in it's fallback function. For security reasons, the send method (used in the vault function) limits gas to 2300. This is incompatible with how Allocations accounts handle funds. However, we're working to enhance Allocations in the coming weeks to enable this kind of workflow.

As you probably recognize, the workaround for this is sending from vault to a vanilla address, and then from that address to allocations, but we know that's not very pretty and we're eager to fix it

# Vote Creation Explanation
The different UX for majority and non-majority token holders is due to forwarding behavior. When the Aragon Wrapper forwards a transaction from a majority token holder, it sort of "pre-calculates" the tx since it already knows the vote will succeed, and if there's a contract error, it fails silently, with the panel just closing. If the action is forwarded by an account that doesn't hold a majority of tokens, the action is forwarded naively with no pre-calculation, and then the contract error is only exposed if the vote passes and a user attempts to execute the action.

Thanks again for taking a look at our project and testing it out! Let us know if you're curious about anything else, and  you're welcome to chat further with us on keybase as well.

**Comment by sepu85** [comment] 2019-05-10 18:01
Thanks for your promt response @topocount

Hope the fix will arrive soon. I'll keep an eye on it 😃

**Comment by stellarmagnet** [comment] 2019-06-11 14:33
This will bn covered in as a result of the research work in this ticket: #856 

So I'm closing this one

**Closed by stellarmagnet** 2019-06-11 14:33 UTC
