### ISSUE TITLE
Projects app does not authorize GitHub

### ISSUE THREAD

**Issue by burrrata** [AutarkLabs/planning-suite#907] opened 2019-05-10 20:38 UTC
It worked the first time, but then I cleared the application cache and it wouldn't let me sign in any more. Clicking "Signin in with GitHub" opens the auth window, but then it closes right away. Restarted the computer, but the bug persisted. Went to GitHub and revoked That Planning Suite from the Authorized OAuth Apps. Then the Projects app allowed me to go through the full "Signin in with GitHub" flow, but after signing in it just returned to the screen that has the "Signin in with GitHub" button. Clicking to sign in again repeats the original error when the auth window opens and then immediately closes, but does not sign in.

**Comment by stellarmagnet** [comment] 2019-05-10 22:07
@burrrata can you please share the link to the DAO in question so we can investigate?

**Comment by burrrata** [comment] 2019-05-10 22:10
1Hive 🐝
- https://rinkeby.aragon.org/#/0xe520428C232F6Da6f694b121181f907931fD2211/0xc2555abaed3797b52248e814172d2bea6728e542

**Comment by topocount** [comment] 2019-05-10 22:42
This is a duplicate of issue #896. I haven't been able to replicate this reliably yet, though

**Comment by burrrata** [comment] 2019-05-10 22:43
Someone else in our org had the same issue an hour after I did. Not sure what's causing it though.

**Comment by topocount** [comment] 2019-05-10 22:45
@burrrata Are you able to authenticate in an icognito browser window?

**Comment by burrrata** [comment] 2019-05-10 22:49
No. The exact same thing happened. Authenticated, then the error happened.

**Comment by stellarmagnet** [comment] 2019-05-10 22:54
@burrrata can you identify an action you took from the time it used to work, from when it didnt? e.g. removing a repo was the last thing you could do in the projects app?

**Comment by burrrata** [comment] 2019-05-11 00:16
@lkngtn set the DAO up so he's probably the best person to ask. Originally the org needed to vote to add and remove repos from the Projects app. Then we changed the permissions so that all members had the permission to add or remove repos. Ever since then it seems to be broken?

**Comment by 0xGabi** [comment] 2019-05-11 02:34
@stellarmagnet @topocount If I remember correctly, last action prior to that was Luke approved an issue (with bounty) that I had have previously submitted work for review

**Comment by 0xGabi** [comment] 2019-05-11 02:36
Link to the [Issue Detail](https://rinkeby.aragon.org/#/0xe520428C232F6Da6f694b121181f907931fD2211/0xc2555abaed3797b52248e814172d2bea6728e542)



<img width="1152" alt="image" src="https://user-images.githubusercontent.com/9082013/57564051-44dd3f00-737c-11e9-92d1-280423961c35.png">

**Comment by lkngtn** [comment] 2019-05-14 16:36
Let me know if there is anything we can do (like granting permissions in the org) that will help you guys nail down this issue.

**Comment by topocount** [comment] 2019-05-14 19:24
@lkngtn We have the root cause pegged. We started on a possible fix for this Friday, before we were confident what the problem was, so now we're going to move forward with testing it a bit more thoroughly and deploying it hopefully today or tomorrow.

**Comment by topocount** [comment] 2019-05-16 04:20
Hey @lkngtn quick update. We deployed several fixes today, but apparently our local replication and patch didn't reflect what happened in the 1Hive project app. We're prioritizing this now. Thanks for your patience and understanding!

**Comment by topocount** [comment] 2019-05-16 21:33
@lkngtn, @0xGabi and @burrrata we've deployed a contract-level fix after replicating the exact error in another rinkeby-deployed dao, and verified that upgrading to this fix will get Projects back up and running. You can upgrade the 1Hive Projects app here: https://rinkeby.aragon.org/#/0xe520428C232F6Da6f694b121181f907931fD2211/apps?p=installed.tps-projects.open.aragonpm.eth

**Comment by lkngtn** [comment] 2019-05-16 23:01
Cool I just upgraded and logged in to test. Seemed to work, asking the other members to validate as well. 

Appreciate you guys looking into this and prioritizing a fix! 🐝

**Comment by burrrata** [comment] 2019-05-16 23:14
Just checked and it worked for me!

**Closed** 2019-05-19 20:52 UTC

**Comment by 0xGabi** [comment] 2019-05-21 05:09
Hey @topocount and @stellarmagnet. We are experiencing the same problem on this dao: https://rinkeby.aragon.org/#/meshteam.aragonid.eth

The steps to reproduce were:
1. Install a DAO with the Aragon on-boarding page.
2. Create a Minime Token and make deposit of that token on the finance app.
2. Install project app and permissions [following this guide](https://github.com/AutarkLabs/planning-suite/blob/master/docs/GETTING_STARTED.md).
  2.1. Update settings of project app choosing experience intermediate.
3. Add [this repo](https://github.com/0xGabi/aragon-cli) to the project app.
4. Fund an issue.
5. Request application with other account.

The account that request the application is still signed on GitHub. 

This account randomly sees states:
<img width="1440" alt="Screen Shot 2019-05-21 at 1 56 05 AM" src="https://user-images.githubusercontent.com/9082013/58069650-75875a80-7b6c-11e9-8734-008ab61b9bf2.png">
<img width="1440" alt="Screen Shot 2019-05-21 at 2 05 45 AM" src="https://user-images.githubusercontent.com/9082013/58069881-5937ed80-7b6d-11e9-9392-08419b766e7c.png">
<img width="1440" alt="Screen Shot 2019-05-21 at 1 55 01 AM" src="https://user-images.githubusercontent.com/9082013/58069649-74562d80-7b6c-11e9-829f-5ca2574b47d0.png">

Note: I was able to re-sign again using safari but still not able to do it on Brave.
