### ISSUE TITLE
Projects app - Review Applicant / Review work (back-end)

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#270] opened 2019-01-04 01:41 UTC
This ticket relates to backend logic for the Submit Work and Review Work flow.

**Comment by topocount** [comment] 2019-01-04 02:32
As far as I understand it thus far, the backend of this will literally just be an `external` call in the frontend to and instance (or _the_ instance) of the Bounties Contract.

**Comment by stellarmagnet** [comment] 2019-01-04 02:34
In "Review Work" we have a Quality rating in the UI. Typically the quality rating will deduct from the bounty amount. Not sure if that is going to be technically possible yet?

**Comment by stellarmagnet** [comment] 2019-01-04 02:35
Also, I think we need to maybe post things on the Github issue when the work is submitted etc?

**Comment by topocount** [comment] 2019-01-04 02:41
It's not possible yet because a Standard Bounty's value is not modifiable. We could fork StandardBounties.sol and make this feature part of the roadmap

**Comment by stellarmagnet** [comment] 2019-02-27 14:21
Whenever I accept someone's work submission, the autark tokens in the bounty are not being transferred to their account.

Tested in dev.

Was this ever tested?

**Comment by topocount** [comment] 2019-02-27 17:56
As mentioned in keybase, I've confirmed that the tokens are indeed transferred (starting with the bounty allocation), they are just infinitesmal in value since we've converted the token we issue from one with 0 decimal places to 18 decimal places.

**Closed** 2019-03-29 18:33 UTC
Labels: app: projects
